/**
 * Canonical crop dataset — single source of truth.
 * Consumed by the frontend (static import) and backend (seed script).
 * Months are 1-indexed (1 = January, 12 = December).
 * Calibrated for Denmark's Köppen-Geiger Cfb climate.
 */

export const CROPS = [
  { id: 1,  name_da: "Tomat",        name_en: "Tomato",       category: "vegetable", icon: "🍅", sow_indoor: [2,3],           sow_outdoor: [],             transplant: [5,6],   harvest: [7,8,9],         difficulty: "medium", care_note_da: "Start indendørs 8 uger før sidste frost. Kræver meget sol.",       care_note_en: "Start indoors 8 weeks before last frost. Needs full sun." },
  { id: 2,  name_da: "Agurk",        name_en: "Cucumber",     category: "vegetable", icon: "🥒", sow_indoor: [4],             sow_outdoor: [5],            transplant: [5,6],   harvest: [7,8,9],         difficulty: "medium", care_note_da: "Elsker varme. Plant i vindlæ.",                                   care_note_en: "Loves warmth. Plant in a sheltered spot." },
  { id: 3,  name_da: "Gulerod",      name_en: "Carrot",       category: "vegetable", icon: "🥕", sow_indoor: [],              sow_outdoor: [3,4,5,6,7],    transplant: [],      harvest: [6,7,8,9,10],    difficulty: "easy",   care_note_da: "Løs, stenfri jord giver de bedste gulerødder.",                  care_note_en: "Loose, stone-free soil gives the best carrots." },
  { id: 4,  name_da: "Salat",        name_en: "Lettuce",      category: "vegetable", icon: "🥬", sow_indoor: [3,4],           sow_outdoor: [4,5,6,7,8,9], transplant: [],      harvest: [5,6,7,8,9,10],  difficulty: "easy",   care_note_da: "Sår løbende for kontinuerlig høst. Bolter i varme.",            care_note_en: "Sow successively for continuous harvest. Bolts in heat." },
  { id: 5,  name_da: "Ærter",        name_en: "Peas",         category: "vegetable", icon: "🫛", sow_indoor: [],              sow_outdoor: [3,4,5],        transplant: [],      harvest: [6,7,8],         difficulty: "easy",   care_note_da: "Sæt pinde til støtte. Høst regelmæssigt for flere bælge.",      care_note_en: "Add supports. Harvest regularly for more pods." },
  { id: 6,  name_da: "Bønner",       name_en: "Beans",        category: "vegetable", icon: "🫘", sow_indoor: [],              sow_outdoor: [5,6],          transplant: [],      harvest: [7,8,9],         difficulty: "easy",   care_note_da: "Sår ikke før jordens temperatur er over 10°C.",                  care_note_en: "Don't sow until soil temperature exceeds 10°C." },
  { id: 7,  name_da: "Squash",       name_en: "Courgette",    category: "vegetable", icon: "🫑", sow_indoor: [4,5],           sow_outdoor: [5],            transplant: [5,6],   harvest: [7,8,9],         difficulty: "easy",   care_note_da: "Én plante giver masser. Høst mens de er små.",                   care_note_en: "One plant gives plenty. Harvest while small." },
  { id: 8,  name_da: "Rødkål",       name_en: "Red Cabbage",  category: "vegetable", icon: "🪴", sow_indoor: [2,3],           sow_outdoor: [4],            transplant: [4,5],   harvest: [8,9,10],        difficulty: "medium", care_note_da: "Beskyt mod kålsommerfugl med fiberdug.",                         care_note_en: "Protect against cabbage white butterfly with fleece." },
  { id: 9,  name_da: "Spinat",       name_en: "Spinach",      category: "vegetable", icon: "🥗", sow_indoor: [],              sow_outdoor: [3,4,5,6,7,8,9], transplant: [],    harvest: [4,5,6,7,8,9,10], difficulty: "easy",  care_note_da: "Hurtigvoksende. Vanding er vigtigt i varmt vejr.",              care_note_en: "Fast growing. Watering is important in warm weather." },
  { id: 10, name_da: "Radise",       name_en: "Radish",       category: "vegetable", icon: "🔴", sow_indoor: [],              sow_outdoor: [3,4,5,6,7,8,9], transplant: [],    harvest: [4,5,6,7,8,9,10], difficulty: "easy",  care_note_da: "Klar på 3-4 uger. Perfekt mellemafgrøde.",                     care_note_en: "Ready in 3–4 weeks. Perfect gap filler." },
  { id: 11, name_da: "Porre",        name_en: "Leek",         category: "vegetable", icon: "🧅", sow_indoor: [1,2],           sow_outdoor: [4],            transplant: [5,6],   harvest: [9,10,11,12],    difficulty: "medium", care_note_da: "Plant dybt for lange hvide skafter.",                            care_note_en: "Plant deep for long white shanks." },
  { id: 12, name_da: "Løg",          name_en: "Onion",        category: "vegetable", icon: "🧅", sow_indoor: [1,2],           sow_outdoor: [3,4],          transplant: [4,5],   harvest: [8,9],           difficulty: "medium", care_note_da: "Lad toppen falde naturligt inden høst.",                        care_note_en: "Allow tops to fall naturally before harvesting." },
  { id: 13, name_da: "Hvidløg",      name_en: "Garlic",       category: "vegetable", icon: "🧄", sow_indoor: [],              sow_outdoor: [10,11],        transplant: [],      harvest: [7],             difficulty: "easy",   care_note_da: "Plant om efteråret for den bedste høst næste sommer.",          care_note_en: "Plant in autumn for the best summer harvest." },
  { id: 14, name_da: "Kartofler",    name_en: "Potatoes",     category: "vegetable", icon: "🥔", sow_indoor: [],              sow_outdoor: [4,5],          transplant: [],      harvest: [7,8,9],         difficulty: "easy",   care_note_da: "Hypning øger udbyttet. Tidligkartofler sættes i april.",        care_note_en: "Earthing up increases yield. Early potatoes go in April." },
  { id: 15, name_da: "Jordbær",      name_en: "Strawberry",   category: "fruit",     icon: "🍓", sow_indoor: [1,2],           sow_outdoor: [3],            transplant: [3,4],   harvest: [6,7],           difficulty: "easy",   care_note_da: "Dæk med halm under frugtsætning.",                              care_note_en: "Mulch with straw when fruiting begins." },
  { id: 16, name_da: "Basilikum",    name_en: "Basil",        category: "herb",      icon: "🌿", sow_indoor: [3,4],           sow_outdoor: [5],            transplant: [5,6],   harvest: [6,7,8,9],       difficulty: "medium", care_note_da: "Elsker varme. Høst regelmæssigt for at undgå blomstring.",      care_note_en: "Loves warmth. Harvest regularly to prevent flowering." },
  { id: 17, name_da: "Persille",     name_en: "Parsley",      category: "herb",      icon: "🌱", sow_indoor: [3],             sow_outdoor: [4,5],          transplant: [],      harvest: [6,7,8,9,10],    difficulty: "easy",   care_note_da: "Langsom spiring — op til 4 uger. Blød frøene i vand først.",  care_note_en: "Slow to germinate — up to 4 weeks. Pre-soak seeds." },
  { id: 18, name_da: "Dild",         name_en: "Dill",         category: "herb",      icon: "🌾", sow_indoor: [],              sow_outdoor: [4,5,6,7],      transplant: [],      harvest: [6,7,8,9],       difficulty: "easy",   care_note_da: "Sår direkte. Lider ikke godt af udplantning.",                  care_note_en: "Sow direct. Dislikes being transplanted." },
  { id: 19, name_da: "Purløg",       name_en: "Chives",       category: "herb",      icon: "🌱", sow_indoor: [2,3],           sow_outdoor: [4],            transplant: [],      harvest: [5,6,7,8,9,10],  difficulty: "easy",   care_note_da: "Flerårig. Klip ned til 5 cm for fornyet vækst.",               care_note_en: "Perennial. Cut back to 5 cm for regrowth." },
  { id: 20, name_da: "Timian",       name_en: "Thyme",        category: "herb",      icon: "🌿", sow_indoor: [2,3],           sow_outdoor: [5],            transplant: [],      harvest: [6,7,8,9,10],    difficulty: "easy",   care_note_da: "Flerårig. Tørrer godt. Plant i veldrænet jord.",               care_note_en: "Perennial. Dries well. Plant in well-drained soil." },
  { id: 21, name_da: "Broccoli",     name_en: "Broccoli",     category: "vegetable", icon: "🥦", sow_indoor: [3,4],           sow_outdoor: [],             transplant: [5,6],   harvest: [7,8,9],         difficulty: "medium", care_note_da: "Høst hoved inden blomstring. Sideskud følger.",                 care_note_en: "Harvest head before it flowers. Side shoots will follow." },
  { id: 22, name_da: "Blomkål",      name_en: "Cauliflower",  category: "vegetable", icon: "🌸", sow_indoor: [2,3],           sow_outdoor: [],             transplant: [4,5],   harvest: [7,8,9],         difficulty: "hard",   care_note_da: "Fold blade hen over kålen for at beskytte farven.",             care_note_en: "Fold leaves over the curd to protect colour." },
  { id: 23, name_da: "Rødbede",      name_en: "Beetroot",     category: "vegetable", icon: "🫐", sow_indoor: [],              sow_outdoor: [4,5,6],        transplant: [],      harvest: [7,8,9,10],      difficulty: "easy",   care_note_da: "Tynd ud til 10 cm. De udtyndte planter kan spises.",            care_note_en: "Thin to 10 cm apart. Thinnings are edible." },
  { id: 24, name_da: "Majs",         name_en: "Sweetcorn",    category: "vegetable", icon: "🌽", sow_indoor: [4,5],           sow_outdoor: [5],            transplant: [5,6],   harvest: [8,9],           difficulty: "medium", care_note_da: "Plant i blok — ikke i rækker — for bedre bestøvning.",         care_note_en: "Plant in a block — not rows — for better pollination." },
  { id: 25, name_da: "Peberfrugter", name_en: "Peppers",      category: "vegetable", icon: "🌶️", sow_indoor: [2,3],          sow_outdoor: [],             transplant: [5,6],   harvest: [8,9],           difficulty: "hard",   care_note_da: "Kræver lang sæson. Start tidligt indendørs.",                   care_note_en: "Needs a long season. Start early indoors." },
  { id: 26, name_da: "Grønkål",      name_en: "Kale",         category: "vegetable", icon: "🥬", sow_indoor: [3,4],           sow_outdoor: [5],            transplant: [5,6],   harvest: [10,11,12,1,2],  difficulty: "easy",   care_note_da: "Smager bedre efter frost. Overlever danske vintre.",           care_note_en: "Tastes better after frost. Survives Danish winters." },
  { id: 27, name_da: "Hindbær",      name_en: "Raspberry",    category: "fruit",     icon: "🫐", sow_indoor: [],              sow_outdoor: [10,11,12,1,2,3], transplant: [],   harvest: [7,8,9],         difficulty: "easy",   care_note_da: "Beskær gamle skud efter høst. Binder til støtte.",              care_note_en: "Prune old canes after harvest. Tie in to supports." },
  { id: 28, name_da: "Ribs",         name_en: "Currant",      category: "fruit",     icon: "🍇", sow_indoor: [],              sow_outdoor: [10,11,12,1,2,3], transplant: [],   harvest: [7,8],           difficulty: "easy",   care_note_da: "Stiklingerne slår let rod. Del eksisterende buske.",            care_note_en: "Cuttings root easily. Divide existing bushes." },
  { id: 29, name_da: "Rucola",       name_en: "Rocket",       category: "vegetable", icon: "🥗", sow_indoor: [],              sow_outdoor: [4,5,6,7,8],    transplant: [],      harvest: [5,6,7,8,9,10],  difficulty: "easy",   care_note_da: "Sår løbende. Bolter hurtigt i varmen.",                        care_note_en: "Sow successively. Bolts quickly in heat." },
  { id: 30, name_da: "Selleri",      name_en: "Celery",       category: "vegetable", icon: "🌿", sow_indoor: [2,3],           sow_outdoor: [],             transplant: [5],     harvest: [8,9,10],        difficulty: "hard",   care_note_da: "Kræver fugtig, næringsrig jord og lang vækstperiode.",          care_note_en: "Needs moist, rich soil and a long growing period." },
];
